version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  javascript:
    image: node
    tty: true
    volumes:
      - ./javascript:/app
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
  python:
    build: 
      context: ./python
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./python:/app
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"